import { motion } from 'motion/react'
import { Download } from 'lucide-react'
import { User, Transaction, TrustScore } from '../../types'

interface DashboardHeaderProps {
    user: User
    transactions: Transaction[]
    score: TrustScore
}

export function DashboardHeader({ user, transactions, score }: DashboardHeaderProps) {
    const handleDownloadReport = () => {
        const reportContent = `
=========================================
FINUI FINANCIAL TRUST REPORT
=========================================
Date: ${new Date().toLocaleDateString()}

USER PROFILE
-----------------------------------------
Name: ${user.name}
Email: ${user.email}
Phone: ${user.phone || 'N/A'}
Business Type: ${user.businessType || 'N/A'}

FINANCIAL SUMMARY
-----------------------------------------
Available Balance: UGX ${user.balance.toLocaleString()}
Total Savings: UGX ${user.savingsBalance.toLocaleString()}
Credit Tier: Tier ${user.creditTier}

TRUST SCORE: ${score.overall}/100
-----------------------------------------
Income Regularity: ${score.breakdown.regularity}%
Consistency: ${score.breakdown.consistency}%
Savings Stability: ${score.breakdown.stability}%

Recommendation: ${score.recommendation}

RECENT TRANSACTIONS (Last 30)
-----------------------------------------
${transactions.slice(0, 30).map(tx => `${new Date(tx.date).toLocaleDateString()} | ${tx.type === 'credit' ? '+' : '-'} UGX ${tx.amount.toLocaleString()} | ${tx.category}`).join('\n')}

=========================================
This document serves as a verifiable financial 
history generated by Finui.
=========================================
    `.trim()

        const blob = new Blob([reportContent], { type: 'text/plain' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `${user.name.replace(/\s+/g, '_')}_Financial_Report.txt`
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
    }

    return (
        <div className="relative bg-emerald-600 text-white rounded-[3rem] shadow-xl overflow-hidden">
            <div className="p-8 md:p-12 flex flex-col md:flex-row justify-between items-start md:items-center gap-6 relative z-10">
                <div>
                    <motion.p
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        className="text-emerald-100 text-lg mb-1 font-medium"
                    >
                        Welcome back,
                    </motion.p>
                    <motion.h1
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.1 }}
                        className="text-4xl md:text-5xl font-black tracking-tight"
                    >
                        {user.name}
                    </motion.h1>
                </div>
                <div className="flex flex-col md:flex-row gap-6 items-start md:items-center">
                    <button
                        onClick={handleDownloadReport}
                        className="bg-white/10 hover:bg-white/20 text-white border border-white/20 px-6 py-3 rounded-2xl flex items-center gap-2 transition-all font-bold text-sm backdrop-blur-md"
                    >
                        <Download size={20} />
                        Download Report
                    </button>
                    <div className="bg-white/20 rounded-[2rem] p-8 backdrop-blur-xl min-w-[300px] border border-white/10 shadow-2xl">
                        <p className="text-emerald-100 text-xs mb-2 font-black uppercase tracking-widest">Available Balance</p>
                        <h2 className="text-4xl font-black">UGX {user.balance.toLocaleString()}</h2>
                    </div>
                </div>
            </div>

            {/* Decorative elements */}
            <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full -mr-20 -mt-20 blur-3xl"></div>
            <div className="absolute bottom-0 left-0 w-64 h-64 bg-emerald-400/20 rounded-full -ml-20 -mb-20 blur-3xl"></div>

            {/* Creative Bottom Edge */}
            <div className="absolute bottom-0 left-0 w-full h-12 overflow-hidden pointer-events-none">
                <svg className="absolute bottom-0 w-full h-12 text-white/5" viewBox="0 0 1440 100" fill="currentColor" preserveAspectRatio="none">
                    <path d="M0,100 C480,0 960,0 1440,100 L1440,100 L0,100 Z" />
                </svg>
            </div>
        </div>
    )
}
